import { StyleSheet, Dimensions } from "react-native";
const { height, width } = Dimensions.get('window');
export const styles = StyleSheet.create({
    itemstyle: {
        width: '90%',
        height: 40,
    },
    boxx: {
        marginTop: 100,
        flex: 1,
    },
    boxer: {
        flex: 1,
        alignItems: 'center'
    },
    itemstyle: {
        backgroundColor: 'red',
        fontSize: 20,
    },
    picker: {
        width: '90%',
        backgroundColor: 'transparent',
        borderColor: 'red',
        borderWidth: 2,
        color: 'black',
        fontSize: 50,

    },
    boxcont: {
        width: '90%',
        height: 60,
        backgroundColor: 'transparent',
        borderColor: 'black',
        borderWidth: 2,
        marginTop: 20,
        borderRadius: 18,
    },
    boxconta: {
        width: '90%',
        height: 60,
        backgroundColor: 'transparent',
        borderColor: 'black',
        borderWidth: 1,
        marginTop: 20,
        borderRadius: 18,
        textAlign: 'center',
        fontSize: 20,
    },
    boxcorner: {
        width: '90%',
        height: 60,
        backgroundColor: 'transparent',
        borderColor: 'black',
        borderWidth: 1,
        marginTop: 20,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
    },
    idan: {
        width: '80%',
        backgroundColor: 'black',
        borderWidth: 2,
        borderColor: 'white',
        borderRadius: 15,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
        right: 0,
    },
    idancover: {
        width: '100%',
        marginTop: 0,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonin: {
        fontSize: 20,
        fontWeight: '700',
        color: 'white',
    },
    stopl: {
        textAlign: 'center',
        fontSize: 19,
        fontWeight: '600',
        color: 'black',
    },
    modalcontain: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',

    },
    modalcontent: {
        alignItems: 'center',
        width: '90%',
        height: 'auto',
        justifyContent: "space-around",
    },
    modaltext: {
        fontSize: 20,
        fontWeight: '600',
        color: 'black',
        fontFamily:'inter',
        marginTop: 80,
        marginBottom: 40,
    },
    imgsrc: {
        width: 200,
        height: 200,
        backgroundColor: 'white',
        marginLeft: 10,
    },
    pinback: {
        flex: 1,
        backgroundColor: '#00000040'
    },
    textmod: {
        textAlign: 'center',
        fontSize: 20,
        fontWeight: '700',
        margin: 10,
        fontFamily: 'inter-Medium'
    },
    pinmod: {
        width: '100%',
        height: 'auto',
        backgroundColor: '#ffffff',
        position: 'absolute',
        bottom: 0,

    },
    pinmodal: {
        width: '100%',
        height: 50,
        flexDirection: 'row',
        justifyContent: 'space-around',

    },
    inputmod: {
        width: '20%',
        height: '90%',
        borderColor: 'black',
        borderWidth: 0,
        color: 'black',
        borderRadius: 10,
        textAlign: 'center',
        fontSize: 20,
        fontWeight: '500',
        marginBottom: 15,
        backgroundColor:'#00000010'
    },
    small: {
        height: 25,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
    pressmall: {
        width: 25,
        height: 25,
        borderRadius: 20,
        backgroundColor: '#ffffff',
        flexDirection: 'row',
        justifyContent: 'center',
        marginRight: 10,
        marginTop: 4,
        alignItems: 'center',
    },
    numberbox: {
        width: width,
        height: 280,
        display: 'flex',
        flexDirection: 'row',
        backgroundColor: '#00000020',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        marginTop: 20,
        paddingVertical: 20,
        //   position:'absolute',
        //  bottom:0,
    },
    numpress: {
        width: width * 0.3,
        height: 50,
        backgroundColor: 'white',
        marginBottom: 10,
        borderRadius: 5,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center'
    },
    numpres: {
        width: width * 0.3,
        height: 50,
        marginBottom: 10,
        borderRadius: 15,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center'
    },
    boxcenter: {
        width: '70%',
        height: 70,
        backgroundColor: 'white',
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        borderColor: 'grey',
        borderWidth: 0.5,
        borderRadius: 8,
        marginBottom: 35,
    },
    pleasewait: {
        fontFamily: 'inter',
        fontSize: 17,
        fontWeight: '700'
    },
    imageContainer: {
        width: 60,
        height: '100%',
        borderColor:'black',
        borderWidth:0,
        borderRadius:10,
    },
    selectedImage: {
        width: 60,
        height: '100%',
        borderColor:'#753ff6',
        borderRadius:10,
        borderWidth:4,
    },
    datacont: {
        display: 'flex',
        flexDirection:'row',
        justifyContent:'space-around',
        alignItems:'center',
        width: '100%',
        height: 60,
        marginTop:5,
        
    },
    contactchoose:{
        display: 'flex',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        width: '100%',
        height: 60,
        marginTop:5,
    }
})